model = "gpt-5"
model_provider = "openai-chat-completions"
preferred_auth_method = "apikey"


[model_providers.openai-chat-completions]
name = "OpenAI using Chat Completions"
base_url = "https://agentrouter.org/v1"
env_key = "sk-CRPYoiHLSDsM2kV0nY0iJoj86msts0cUxLy7iMk5Sx9AMt87"
wire_api = "chat"
query_params = {}
stream_idle_timeout_ms = 300000